Public Class Variables
    Public Shared PercorsoBackup As New KeyIni With {.Percorso = "BACKUP", .Key = "Percorso"}
    Public Shared Esecuzione As New KeyIni With {.Percorso = "AVVIO", .Key = "Esecuzione"}
    Public Shared Software As New KeyIni With {.Percorso = "AVVIO", .Key = "Software"}
    Public Shared LogoPenta As New KeyIni With {.Percorso = "AVVIO", .Key = "LogoPenta"}
    Public Shared PercorsoDatabase As New KeyIni With {.Percorso = "DB", .Key = "Percorso"}
    Public Shared UnitaArchiviazione As New KeyIni With {.Percorso = "DB", .Key = "UnitaArchiviazione"}
    Public Shared UtenteDatabase As New KeyIni With {.Percorso = "DB", .Key = "User"}
    Public Shared PasswordDatabase As New KeyIni With {.Percorso = "DB", .Key = "Password"}
    Public Shared TipoArchiviazione As New KeyIni With {.Percorso = "DB", .Key = "Tucker"}
    Public Shared IndirizzoIpDatabase As New KeyIni With {.Percorso = "DB", .Key = "IP"}
    Public Shared mct As New KeyIni With {.Percorso = "STAMPANTI", .Key = "MCT"}
    Public Shared ditron As New KeyIni With {.Percorso = "STAMPANTI", .Key = "Ditron"}
    Public Shared epson As New KeyIni With {.Percorso = "STAMPANTI", .Key = "Epson"}
    Public Shared CausaleAnnullo As New KeyIni With {.Percorso = "STAMPANTI", .Key = "CausaleAnnullo"}
    Public Shared RepartoAnnullo As New KeyIni With {.Percorso = "STAMPANTI", .Key = "RepAnnullo"}
    Public Shared PercorsoMultiDriver As New KeyIni With {.Percorso = "STAMPANTI", .Key = "PercorsoMultidriver"}
    Public Shared PercorsoWinEcr As New KeyIni With {.Percorso = "STAMPANTI", .Key = "PercorsoWinEcr"}
    Public Shared PercorsoFpMate As New KeyIni With {.Percorso = "STAMPANTI", .Key = "PercorsoFpMate"}
    Public Shared DettaglioNScontrino As New KeyIni With {.Percorso = "STAMPANTI", .Key = "DettaglioNScontrino"}
    Public Shared DettaglioCapi As New KeyIni With {.Percorso = "STAMPANTI", .Key = "DettaglioCapi"}
    Public Shared ScontrinoParlante As New KeyIni With {.Percorso = "STAMPANTI", .Key = "ScontrinoParlante"}
    Public Shared Postazione As New KeyIni With {.Percorso = "STAMPANTI", .Key = "Postazione"}
    Public Shared FatturazioneElett As New KeyIni With {.Percorso = "MODULI", .Key = "FattElett"}
    Public Shared SpeakerNomePronto As New KeyIni With {.Percorso = "MODULI", .Key = "SpeakerPronto"}
    Public Shared InvioSYNC As New KeyIni With {.Percorso = "MODULI", .Key = "InvioSYNC"}
    Public Shared UrlFatturazione As New KeyIni With {.Percorso = "MODULI", .Key = "UrlFatturazione"}
    Public Shared VersioneSYNC As New KeyIni With {.Percorso = "FATTEL", .Key = "VersioneSYNC"}
    Public Shared PercorsoFatture As New KeyIni With {.Percorso = "FATTEL", .Key = "percorsofatt"}
    Public Shared PercorsoSYNC As New KeyIni With {.Percorso = "SYNC", .Key = "PercorsoSYNC"}
    Public Shared PercorsoMacroMiniMouse As New KeyIni With {.Percorso = "SYNC", .Key = "PercorsoMacro"}
    Public Shared CoordinateXInvio As New KeyIni With {.Percorso = "SYNC", .Key = "CoordinateXInvio"}
    Public Shared CoordinateYInvio As New KeyIni With {.Percorso = "SYNC", .Key = "CoordinateYInvio"}
    Public Shared CoordinateXErrore As New KeyIni With {.Percorso = "SYNC", .Key = "CoordinateXErrore"}
    Public Shared CoordinateYErrore As New KeyIni With {.Percorso = "SYNC", .Key = "CoordinateYErrore"}
    Public Shared CoordinateButtonXFatturazione As New KeyIni With {.Percorso = "SYNC", .Key = "CoordinateButtonXFatturazione"}
    Public Shared CoordinateButtonYFatturazione As New KeyIni With {.Percorso = "SYNC", .Key = "CoordinateButtonYFatturazione"}
    Public Shared CoordinateButtonXInvio As New KeyIni With {.Percorso = "SYNC", .Key = "CoordinateButtonXInvio"}
    Public Shared CoordinateButtonYInvio As New KeyIni With {.Percorso = "SYNC", .Key = "CoordinateButtonYInvio"}
    Public Shared CoordinateButtonXChiusura1 As New KeyIni With {.Percorso = "SYNC", .Key = "CoordinateButtonXChiusura1"}
    Public Shared CoordinateButtonYChiusura1 As New KeyIni With {.Percorso = "SYNC", .Key = "CoordinateButtonYChiusura1"}
    Public Shared CoordinateButtonXChiusura2 As New KeyIni With {.Percorso = "SYNC", .Key = "CoordinateButtonXChiusura2"}
    Public Shared CoordinateButtonYChiusura2 As New KeyIni With {.Percorso = "SYNC", .Key = "CoordinateButtonYChiusura2"}
    Public Shared CoordinateButtonXChiusura3 As New KeyIni With {.Percorso = "SYNC", .Key = "CoordinateButtonXChiusura3"}
    Public Shared CoordinateButtonYChiusura3 As New KeyIni With {.Percorso = "SYNC", .Key = "CoordinateButtonYChiusura3"}
    Public Shared Aggiornamenti As New KeyIni With {.Percorso = "UPDATE", .Key = "Aggiornamenti"}
    Public Shared DataProssimoAggiornamento As New KeyIni With {.Percorso = "UPDATE", .Key = "DataAggiornamento"}
    Public Shared ForzareAggiornamento As New KeyIni With {.Percorso = "UPDATE", .Key = "ForzareAggiornamento"}
End Class
